// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('C:/Users/galfan/Documents/web-dev/me/src/components/counter.vue')['default']
    Foldeable: typeof import('C:/Users/galfan/Documents/web-dev/me/src/components/foldeable.vue')['default']
    Footer: typeof import('C:/Users/galfan/Documents/web-dev/me/src/components/Footer.vue')['default']
    HeadBar: typeof import('C:/Users/galfan/Documents/web-dev/me/src/components/head-bar.vue')['default']
    MenuContainer: typeof import('C:/Users/galfan/Documents/web-dev/me/src/components/post-container/menu-container.vue')['default']
    MousePos: typeof import('C:/Users/galfan/Documents/web-dev/me/src/components/MousePos.vue')['default']
    PostContainer: typeof import('C:/Users/galfan/Documents/web-dev/me/src/components/post-container/index.vue')['default']
    TopBar: typeof import('C:/Users/galfan/Documents/web-dev/me/src/components/TopBar.vue')['default']
  }
}

export { }
